### ISSUE TITLE
Test that compare functions don't fail with incomplete inputs

### ISSUE THREAD

**Issue by batpad** [mapbox/osm-compare#103]
There are several cases when we pass "incomplete" inputs into compare functions. Compare functions should exit gracefully and not throw errors if any of the following is missing:

 - Either `oldVersion` or `newVersion`: this is quite obvious - either will be missing if the feature is created or deleted. We need tests to make sure no function throws an error in this case.

 - Missing geometries: We want to be able to run compare functions (potentially) on features where we do not have or are unable to get full geometries. Compare functions MUST handle cases of `geometry` being null.

We need tests for the above ^ - a set of fixtures with each of these cases - i.e. `oldVersion` missing, `newVersion` missing, and geometries missing (set to `null`) - the test suite should run these fixtures against all compare functions and ensure that none throw errors.

cc @amishas157 @geohacker

**Comment by amishas157** [comment]
PR merged : https://github.com/mapbox/osm-compare/pull/104

cc @batpad

**Comment by geohacker** [comment]
Thank you @amishas157 @batpad!
