### ISSUE TITLE
Using context for detecting harmful features

### ISSUE THREAD

**Issue by amishas157** [mapbox/osm-compare#112]
@bkowshik brought an interesting idea of context based detection for flagging harmful features. 
Following are notes from the discussion we had on this idea :

So far we haven't worked on any feature detector where we use context while doing any detection.

Context can have different meaning here. It can refer to surrounding area where a feature is created or it can also refer to the time when a feature is created. Following are few examples to understand the idea of context better:
  - Say there is a lake having all valid tags and looking 💯 if checked individually. But what if it is overlapping with other features in an area which makes it as bad bad  feature. Ref: A [lake](https://osmcha.mapbox.com/46963151/) was created in Manhattan city overlapping many buildings.
 - Another example of context can be distinguishing areas which are well mapped (for example: Germany , San Francisco) and which are not (For example: India). So now thinking about this, say someone adds lakes , hills in places which are well mapped. That will appear to be much more suspicious than if someone adds these kind of features in not so well mapped areas. Because there is a possibility that these kind of features could be missing from these areas. But it's not expected these feature addition in well mapped areas.
 - Talking about time based context: For example it won't be common, people adding new airports to map now. Because we expect that these kind of features should be added to OSM by now and any new addition should be suspicious.
 
☝️ can help in following ways:
  - To create suspicious feature which otherwise looks good.
  - It also helps in flagging critical issues.

@geohacker @batpad @planemad Would be great to hear your thoughts on above and how can we leverage context more to find harmful features.

**Comment by willemarcel** [comment]
@amishas157 It's really a good idea! Context is very important.

**Comment by bkowshik** [comment]
Breaking out overlapping features into a separate ticket: https://github.com/mapbox/osm-compare/issues/129

**Comment by bkowshik** [comment]
A new city or a town created within the radius of the city could be problematic. Ideally, `town` shouldn't be tagged inside the `city`. It can be tagged as `place=neighbourhood/suburb`. Ex:

- http://osmcha.mapbox.com/47206420/features/node-4758254638/

A suburb was wrongly tagged as a town which the same user corrected after 5 days. Yay!!! 🎉 

- http://www.openstreetmap.org/node/4758254638/history

The context here could be that a new city cannot exist very close to an exiting city, town, etc. Would be good learning to brainstorm what other features cannot exist close by on the map.

---

cc: @chtnha

**Comment by amishas157** [comment]
Related issues (WIP)
- https://github.com/mapbox/osm-compare/issues/129
- https://github.com/mapbox/osm-compare/issues/131
- https://github.com/mapbox/osm-compare/issues/148

Closing this issue for now. Let's reopen when it's required.
