### ISSUE TITLE
Valid highway tags missing

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-compare#114]
Seeing some valid highway tags missing from https://github.com/mapbox/osm-compare/blob/master/comparators/invalid-highway-tags.js

`highway=milestone` for one. 

@kupendrayadav @bkowshik @amishas157 would it make sense to rely on taginfo for these?

**Comment by geohacker** [comment]
* `highway=traffic_mirror`

**Comment by amishas157** [comment]
This is related to this common tag value CF: https://github.com/mapbox/osm-compare/pull/121 , which looks for tag info and find key-value combination for the primary tags, (right now highway) and flags those features where that value for highway tag is either having frequency less 10000 (which means that particular value has been used with highway tag in osm < 10000 times) or the value is never used.

Will merge the PR, if some features for the same are evident on staging and also turn off invalid-highway-tag combination cf

cc @geohacker

**Comment by willemarcel** [comment]
This PR https://github.com/mapbox/osm-compare/pull/165 solves this
