### ISSUE TITLE
Util for fetching vector tiles

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-compare#130]
Let's write a util to fetch vector tiles and return geojson feature collection so compare functions can use this to check context of what's on the map. Related to  #112 #129 

Here's what I think this should look like:

* util receives vector tile ID, x, y and z. Default vector tile ID to mapbox-streets 
* request for the tile by hitting the maps end point
* use https://github.com/mapbox/vector-tile-js#methods-1 to convert the pbf to geojson
* return the featurecollection

Additionally:
* the util can accept a feature filter https://github.com/mapbox/feature-filter and return only features that satisfy this.

cc @amishas157 @bkowshik @batpad @lukasmartinelli @ian29 @manoharuss

**Comment by ian29** [comment]
got started sketching out a version of this here https://github.com/mapbox/cartography/blob/tools/bin/tile-inspector.js

**Comment by amishas157** [comment]
Done here https://github.com/mapbox/osm-compare/blob/master/lib/get_vector_tile_features.js. Closing.
