### ISSUE TITLE
Adding an Eslint precommit hook

### ISSUE THREAD

**Issue by kepta** [mapbox/osm-compare#151]
I feel this repository is contributed by many people and keeping the code formatting consistent becomes a nightmare.
Adding an auto formatting recommit hook makes life easier for the maintainers and makes the code predictable.

This [PR](https://github.com/mapbox/osm-compare/pull/152) adds this functionality to this repo.

 _*Note: It doesn't break anything just formats the code before a git commit happens.*_

**Comment by kepta** [comment]
This was completed in two phases
https://github.com/mapbox/osm-compare/pull/159
https://github.com/mapbox/osm-compare/pull/153
Closing this.

**Comment by batpad** [comment]
❤️ thank you @kepta !!
