### ISSUE TITLE
highway node dragged

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osm-compare#174]
[This changeset](https://osmcha.mapbox.com/changesets/49445793) dragged a highway node by approximately 1km and created an impossible angle, but wasn't tagged as suspicious by the compare functions.

![captura de tela de 2017-07-21 22-02-01](https://user-images.githubusercontent.com/666291/28487088-5e380e76-6e60-11e7-80da-7ccd33e70b43.png)

**Comment by amishas157** [comment]
@willemarcel Thanks for flagging the issue. But this is a known infrastructural problem. By that I mean, when a node (a part of way) is edited, the newVersion and oldVersion will be reflected only for node and right now there is no way we can grab the information which ways were affected by that. Therefore none of the compare functions flagged this change.

**Comment by willemarcel** [comment]
Thanks @amishas157
