### ISSUE TITLE
Improve new_mapper compare functions with more data points

### ISSUE THREAD

**Issue by bkowshik** [mapbox/osm-compare#19]
The OpenStreetMap API gives the following details on a mapper:
- User ID
- Display name
- Date the account was created
- Description
- Whether the user has agreed to the `contributor-terms`
- Hyperlink to user's gravatar
- Number of `changesets` created
- Number of `traces` done
- Number of `blocks received` and `blocks active`

Currently, we use just the `User ID` to decide whether the mapper is a new mapper or not. But, we could potentially use the following in some way to make a better guess:
- Date the account was created
- Number of `changesets` created
- Number of `traces` done

**Comment by geohacker** [comment]
Stale
