### ISSUE TITLE
Set a flag for suspicious transformations over a certain threshold

### ISSUE THREAD

**Issue by planemad** [mapbox/osm-compare#35]
From #34 

It is possible for compare functions to determine certain suspicious scenarios:
- A whole way was displaced by X distance
- A node in the way was dragged by X distance

A movement greater than X=100 metres is a definite problem and should probably be flagged as `invalid`. Its currently very hard to deduce this by relying on the output score of the compare function.

Given that this has been the most common class of breakage https://github.com/mapbox/vandalism-dynamosm/issues/35 is it may be worth trying to focus on catching these issues first before others.

cc @bkowshik @batpad @mikelmaron

**Comment by mikelmaron** [comment]
So is the answer here to change the vibe score at which this problem is reported? Where is that happening now in the code @planemad @batpad?

**Comment by planemad** [comment]
@mikelmaron we need to think about what a vibe represents, we currently use it as an indication of suspicion, but in certain cases, we can be sure it is definitely bad and the total vibe of a feature currently does not capture that. We could set an arbitrarily high score like `-100`, but as per @batpad a more sensible approach is to just set a flag of `bad` so that it can be treated separately from a suspicious feature.

The score -> vibe reporter is here: https://github.com/mapbox/vandalism-dynamosm/blob/master/util/reporter.js

cc @bkowshik

**Comment by mikelmaron** [comment]
> sensible approach is to just set a flag of bad so that it can be treated separately from a suspicious feature.

is that currently supported? would this automatically put that feature into escalated queue?

**Comment by planemad** [comment]
@mikelmaron not yet.

@batpad what do you think about escalating issues flagged `invalid` directly to the escalation queue? We should be able to start detecting confirmed displacements immediately with this.

**Comment by planemad** [comment]
@batpad following up from voice, lets do this!

- [ ] compare-geojson will set a new `invalid=true` flag for way or node displacements over 100m @planemad

Next we would need show these issues in a separate `invalid` queue in VH2 for review.

cc @bkowshik @mikelmaron

**Comment by geohacker** [comment]
We do flag node drags.
