### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by lxbarth** [mapbox/osm-compare#37]
@bkowshik - could this have a better name? `compare-geojson` is very generic while this project is OSM specific. We don't need to go overly descriptive, but `osm-compare` or similar would better.

**Comment by bkowshik** [comment]
Sure @lxbarth 

`osm-compare` sounds good to me. If we don't have any other potential names by the end of day, I will go ahead and make the change.

cc: @mikelmaron @batpad @geohacker @planemad @maning @chtnha

**Comment by bkowshik** [comment]
Repository renamed to `osm-compare`.
