### ISSUE TITLE
Compare function for long name tag values

### ISSUE THREAD

**Issue by manoharuss** [mapbox/osm-compare#39]
Per chat with @geohacker, idea based [on a diary post on OSM](http://www.openstreetmap.org/user/Harry%20Wood/diary/39400). It would be good to have a compare function to flag when `name=*` tags are given very long to verify in validation. Example: When the name tag value length is more than 40-50 characters.

cc @planemad @bkowshik @geohacker @chtnha

**Comment by willemarcel** [comment]
Solved with https://github.com/mapbox/osm-compare/pull/185
