### ISSUE TITLE
Rename package: compare-geojson -> osm-compare

### ISSUE THREAD

**Issue by planemad** [mapbox/osm-compare#40]
Can we rename the package https://github.com/mapbox/osm-compare/blob/master/package.json for consistency with the repository name?

cc @bkowshik @amishas157

**Comment by batpad** [comment]
Yea, so the module is called `compare-geojson` on `npm`. We should definitely resolve this inconsistency, just pointing out that there is another place where this exists, and it may not be so nice to change the name on `npm`.

**Comment by bkowshik** [comment]
Renamed to `osm-compare` in version: [`4.16.3`](https://www.npmjs.com/package/@mapbox/osm-compare)

**Comment by bkowshik** [comment]
Bumping up to a major version: `5.0.0`

**Comment by bkowshik** [comment]
Fixed with: https://github.com/mapbox/osm-compare/pull/120
