### ISSUE TITLE
Compare function to catch highway=footway

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-compare#64]
Let's quickly wire a compare function to catch features that meet the following:

* highway=footway
* version 1
* by a new user

@batpad @amishas157 @bkowshik

**Comment by geohacker** [comment]
This is in the light of changesets like this https://github.com/mapbox/mapping/issues/259

**Comment by geohacker** [comment]
Per chat @bkowshik: 

* Let's escalate for footways that are added by user accounts created after Dec 23, 2016. This is when Reddit thread announced Pokemon Go uses OSM. https://www.reddit.com/r/TheSilphRoad/comments/5jfnrm/how_to_find_the_new_rural_spawn_points/

**Comment by bkowshik** [comment]
Deployed with https://github.com/mapbox/osm-compare/pull/68

**Comment by bkowshik** [comment]
- Deployed with https://github.com/mapbox/osm-compare/pull/68
- http://osmcha.mapbox.com/features?harmful=False&checked=All&reasons=21

**Comment by geohacker** [comment]
This is done.
