### ISSUE TITLE
Flag any changes in and around null island

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-compare#75]
cc @mapbox/vandals

**Comment by geohacker** [comment]
Here's a bbox we can use `-6.722814455240666 -5.174241507358232 6.570950888668989 5.045358293553775`

**Comment by krishnanammala** [comment]
@geohacker Can we use this 👇  as test cases:

* https://osmcha.mapbox.com/42195460/
* https://osmcha.mapbox.com/42195515/

One of the user created a imaginary island in the middle of the ocean and the community cleaned it up.
