### ISSUE TITLE
Flagging suspicious edits on ocean

### ISSUE THREAD

**Issue by srividyacb** [mapbox/osm-compare#83]
Recently there have been many fantasy edits on ocean where suspicious features are added in the middle of sea. Apart from whats happening on land, we also need to catch these edits and take actions immediately.

Other than `route=ferry` and any other ferry related tags, any new features in the middle of the ocean should be caught and flagged in OSMCha.

![image](https://cloud.githubusercontent.com/assets/3423533/23013856/7c59970e-f452-11e6-927a-b3f9d550dd93.png)
http://osmcha.mapbox.com/45228754/

![image](https://cloud.githubusercontent.com/assets/3423533/23013958/f53d647a-f452-11e6-93ba-c6a907c48675.png)
http://osmcha.mapbox.com/45228653/

cc @mapbox/vandals

**Comment by geohacker** [comment]
@srividyacb great idea! Do you think this is more of a validator in OSM Lint? If we were to write this in osm-compare, we should create a GeoJSON polygon for the ocean where we don't expect any features. 

Related is the compare function that flags edits around null island https://github.com/mapbox/osm-compare/blob/master/comparators/null-island.js

**Comment by srividyacb** [comment]
@geohacker Oceans and Seas are shown as `node` in OSM. To do it in osmlint, does QA-tiles have any polygon for seas and oceans?

**Comment by srividyacb** [comment]
@geohacker 
Per voice with @amishas157 Can we do something like, if any feature coming from dynamosm is not falling in the World countries boundary then it needs to be reviewed. 🤔 

![image](https://cloud.githubusercontent.com/assets/3423533/23017450/52f3d2cc-f460-11e6-96b0-4ed685f46a4b.png)

**Comment by willemarcel** [comment]
good idea!

> Other than route=ferry and any other ferry related tags, any new features in the middle of the ocean should be caught and flagged in OSMCha.

There are some other tags that are common in the ocean, like `man_made=pier`, `seamark:*`, administrative boundaries and wind turbines (`generator:source=wind` and `power=generator`).
