### ISSUE TITLE
Flag new cities and towns

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-compare#86]
I think we should flag any new `place=city` or `place=town`.

cc @amishas157 @bkowshik @manoharuss @batpad @maning

**Comment by krishnanammala** [comment]
@geohacker What about `place=country` . Wiki: https://wiki.openstreetmap.org/wiki/Tag:place%3Dcountry

**Comment by amishas157** [comment]
@geohacker https://github.com/mapbox/osm-compare/pull/87 Added the comparator which checks for a new place tag having `city`, `country` or `town` as value

cc @krishnanammala
