### ISSUE TITLE
Edited a name tag comparator flagging the previous changed.

### ISSUE THREAD

**Issue by maning** [mapbox/osm-compare#92]
From this [changeset](https://osmcha.mapbox.com/46439103/) a [road](https://osmcha.mapbox.com/46439103/features/way-43181417/) was flagged by the `Edited a name` comparator.  But the change did not happen in this changeset but from a [previous changeset](https://osmcha.mapbox.com/46437616/).

@amisha157 @batpad @manoharuss

**Comment by geohacker** [comment]
Will revisit.
