### ISSUE TITLE
Large building threshold too low? 

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-compare#93]
I'm seeing features like https://osmcha.mapbox.com/46511367/features/way-477982666/ come through flagged `Added a large building`. Is the threshold too low? 

@manoharuss @bkowshik can you help verify this?

**Comment by manoharuss** [comment]
@geohacker the area threshold is at 1500m https://github.com/mapbox/osm-compare/blob/master/comparators/large-building.js#L13

Thinking of bumping this upto 4000m and see what comes through. Will make a PR for this.

**Comment by geohacker** [comment]
Fixed in #117
