### ISSUE TITLE
Features on OpenStreetMap with more than one primary tag

### ISSUE THREAD

**Issue by bkowshik** [mapbox/osm-compare#94]
Per voice with @planemad @geohacker @amishas157 

---

We wanted to 👀 what percentage of features on OpenStreetMap have 2 primary tags. There are `26` primary tags. Ex: `building`, `natural`, etc.

- https://wiki.openstreetmap.org/wiki/Map_Features

Using the [key combinations API from TagInfo](https://taginfo.openstreetmap.org/taginfo/apidoc#api_4_key_combinations), we get the percentage of features that have a primary tag also have another primary tag. Ex: `60.05 %` of the `geological` primary tag also have the `natural` primary tag.

<img width="1209" alt="screen shot 2017-03-02 at 5 58 18 pm" src="https://cloud.githubusercontent.com/assets/2899501/23507205/e393d0d6-ff71-11e6-914f-a6228980ce59.png">

Querying the taginfo API for all combinations of the 26 primary tags, we have a correlogram. Ex: `90.66 %` of features with `sport` tag on OpenStreetMap also has the `leisure` tag.

<img width="1067" alt="screen shot 2017-03-02 at 5 57 41 pm" src="https://cloud.githubusercontent.com/assets/2899501/23507204/e3935214-ff71-11e6-8d25-6fa9fe00824b.png">

*NOTE: Cells that are empty represent a zero value.*

| Category | Count |
| --- | --- |
| percentage == 0 | 286 |
| 0 < percentage < 1 | 330 |
| percentage >= 1 | 60 |

**Comment by bkowshik** [comment]
CSV file with counts: https://gist.github.com/bkowshik/e8186f50029226f6585d42d6c23a6c62

**Comment by planemad** [comment]
Amazing stats @bkowshik, this directly gives the probability of any tag combination on OSM. With these 286 invalid and 330 possibly erroneous tag combination, can we already start flagging them?

@Rub21 can you write an osmlint function to filter all existing objects with these tags?

cc @manoharuss

**Comment by bkowshik** [comment]
Thank you @planemad have ticketed out the compare function here: https://github.com/mapbox/osm-compare/issues/96

**Comment by bkowshik** [comment]
The compare function coming along nicely here: https://github.com/mapbox/osm-compare/pull/102

Per https://github.com/mapbox/osm-compare/issues/94#issuecomment-283905597

> @Rub21 can you write an osmlint function to filter all existing objects with these tags?

Next actions on you @Rub21, feel free to open up a ticket on [osmlint](https://github.com/osmlab/osmlint/) and close this issue.
