### ISSUE TITLE
Improving the null_island comparator

### ISSUE THREAD

**Issue by bkowshik** [mapbox/osm-compare#97]
Looked at all the [changesets flagged by the `null_island` compare function](http://osmcha.mapbox.com/?is_suspect=True&is_whitelisted=True&harmful=False&checked=All&reasons=25) on `osmcha-django`.
- A total of `51` changesets are flaggged by the comparator
- `18` changesets were manually reviewed, approx `35%`
- None of the changesets reviewed are problematic.

One of the false positives looks like below. Ex:

<img width="897" alt="screen shot 2017-03-06 at 5 02 47 pm" src="https://cloud.githubusercontent.com/assets/2899501/23608467/79f15164-028f-11e7-823b-b2033f3f7852.png">

Should we reduce the size of the bbox for null island from the current bbox below?

<img width="681" alt="screen shot 2017-03-06 at 5 07 11 pm" src="https://cloud.githubusercontent.com/assets/2899501/23608440/5de6c42c-028f-11e7-85d5-e8cd5dd8c6f6.png">

**Comment by bkowshik** [comment]
cc: @amishas157 @geohacker

**Comment by geohacker** [comment]
@bkowshik - agree. we can make tighten the bbox.
related https://github.com/mapbox/osm-compare/issues/83
